### ISSUE TITLE
Modifier `.none` animation ambiguity

### ISSUE THREAD

**Issue by dmitryd20** [surfstudio/ReactiveDataDisplayManager#236]
`Modifier` protocol has various methods with optional `Animation` parameters. In its implementations `Animation` becomes either `UITableView.RowAnimation` or `CollectionItemAnimation`.

The problem appears when using UITableView modifiers with animation parameter `.none`.  `.none` can be treated both as `Optional.none` and `UITableView.RowAnimation.none`. Following IDE warning:
<img width="655" alt="Снимок экрана 2023-06-20 в 16 21 03" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28758703/fe7253e2-fb90-4cef-a90a-8ec607fb6561">

Even without ambiguity – it is not clear what should users choose if they need no animation - `nil` or `.none`.

Since `UITableView.RowAnimation` already has `.none` case,  is it possible to make `animation` parameter non-optional? In UIColectionView modifiers it can still be optional.

**Comment by NullIsOne** [comment]
When we made animation parameter optional we solved an issue when you really need to disable all animations. We found that `UITableView.RowAnimation.none` is still animated change. So we added optional to resolve this issue. And also we added `UIView.performWithoutAnimation` to completely disable any animations inside `performBatchUpdates` call.

To resolve ambiguity you can simply use `nil` instead of `none` or concrete `UITableView.RowAnimation.none` if you need potentially animated change.

**Comment by Ikeret** [comment]
It's better to use enum for animation parameter:
```swift
enum AnimateOption {
    case animated(UITableView.RowAnimation)
    case none // without animation
}
```

**Comment by NullIsOne** [comment]
Such change is achievable only in 8.0, because its not backward compatible.
We will think about it.
